### ISSUE TITLE
Support Small Size LCD

### ISSUE THREAD

**Issue by iDavidFeng** [dc42/PanelDue#10]
Now，the firmware does not support the Small Size LCD，such as ILI9327 controller.But I wanna a small LCD.A large LCD for a small 3D printer is strange，thanks！

**Comment by dc42** [comment]
A smaller LCD would provide much less functionality, for example less information displayed and no touch keyboard to allow you to enter gcode commands. Even the 3.2" screen that I started out using proved too small, that's why we chose 4.3" as the minimum size supported. But the firmware is open source and the display driver it uses includes support for the IL9327, so feel free to adapt it to a smaller screen if you want.

**Comment by iDavidFeng** [comment]
You mean that,the later codes also support ILI9327?The latest codes contains the driver for ILI9327 or I must copy the driver from the old codes to new code and Rebuild it?

**Comment by dc42** [comment]
I mean that the TFT screen driver in the current source code supports the ILI9327 and a number of other TFT panel driver chips. You define which chip you want to use in file src/hardware/memorysaver.h.

**Comment by iDavidFeng** [comment]
Got it，thanks!
